encoding: UTF-8
timezone: UTC

name: Fingers Crossed
description: Alex Lovell-Troy is writing with his fingers crossed
url: http://fingers.cx
baseurl: /

markdown: rdiscount
permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md
- /scss/
