encoding: UTF-8
timezone: UTC

name: LovellTroy.org
description: Opinions on building stuff from Alex Lovell-Troy
url: http://lovelltroy.org
baseurl: /

markdown: rdiscount
permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md
- /scss/
