name: The Heretic
description: An opinionated Newsletter by Pascal Finette
url: http://theheretic.me

markdown: rdiscount

permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md