name: The Heretic
description: An opinionated Newsletter by Pascal Finette
url: http://theheretic.me
baseurl: /

markdown: rdiscount

permalink: /:year/:month/:day/:title
lsi: false

encoding: UTF-8
paginate: 0

exclude:
- CNAME
- README.md
- /scss/
